feature(triple-reads-backend): Added the initial setup for the backend
benedictdube/triple_reads pull request #2
Opened 2023-08-16 17:27 UTC by Kyle-Pottinger

2023-08-18 10:14 UTC, KalesmatBBD approved these changes

2023-08-19 12:13 UTC, raagakrishna requested changes

2023-08-19 12:13 UTC, raagakrishna commented on .gitignore
> +.env
Let's add "dist/" to this

2023-08-19 15:22 UTC, raagakrishna approved these changes

2023-08-19 15:28 UTC, merged